name = "CDFIntegrals"
uuid = "c315eb13-d14d-45c6-a93f-2ca8f34325ea"
authors = ["ngiann <ngiann@gmail.com> and contributors"]
version = "1.0.2-DEV"

[deps]
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"

[compat]
HCubature = "1.5"
QuadGK = "2.8"
StatsFuns = "1.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
